<footer>
        <div class="brandfooter">
        <img class="logo" src="images/logo.png" alt="Company Logo">
        <h1>TECHYA</h1>            
    </div>
    
    <p class="contact">Contact us:
        <br>
        <a href="https://youtube.com/"><img src="images/youtube-logo.png" alt="YouTube"></a>
        <a href="https://github.com/OpenHLE/Web-Project"><img src="images/github-logo.png" alt="GitHub"></a>
        <a href="mailto:105550542@student.swin.edu.au"><img src="images/mail-logo.png" alt="Email"></a>
    </p>
    <div class="location">
        <p>Our location:</p>
        
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.042153278479!2d105.78157517829588!3d21.03099928045221!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135bfa667a7dee9%3A0x2ac9ba5f99e4f389!2sSwinburne%20Innovation%20Space!5e0!3m2!1svi!2s!4v1740037300397!5m2!1svi!2s" width="200" height="150" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

    <p class="copyright">&copy; <?php echo date('Y'); ?> TECHYA. All rights reserved.</p>
</footer>