<header class="navbar"> 
    <div class="brand">
        <img class="logo" src="images/logo.png">
        <h1>Techya</h1>     
    </div>
            
    <nav>
            
        <ul>
            <li id="home"><a href="index.php">Home</a></li>
            <li id="jobs"><a href="jobs.php">Career</a></li>
            <li id="apply"><a href="apply.php">Apply</a></li>
            <li id="abt"><a href="about.php">About</a></li>
            <li id="enhancement"><a href="enhancement.php">Enhance</a></li>
            <span class="nav-highlight"></span>
        </ul>
                
    </nav>   
</header>